name: Lint and test 

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest black isort codespell
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0
    - run: black . --check
    - run: codespell --quiet-level=2
    - run: isort --recursive .
    - run: pip install -r requirements.txt || true
    - run: pytest .
